theme: ../src

siteConfig:
  url: https://minima.saberjs.org
  author: Author of This Site
  email: author@your-domain.com
  description: Write an awesome description for your new site here. You can edit this line in saber-config.yml. It will appear in your document head meta (for Google search results) site description.

themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about.html
  social:
    twitter: _saberjs
    github: egoist
    rss: true
  disqus: saber-minima

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-generate-feed
    options: 
      atomFeed: true